/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package malyuun_university;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static malyuun_university.AcademicYear_view.rSTableMetro1;

/**
 *
 * @author Xamda Cumar
 */
public class AcademicYear_Form extends javax.swing.JFrame {

    /** Creates new form Locations_Form */
    codes co =new codes();
    String ac,id;
    public void clear(){
        text_ser1.setText("");
        text_yrname.setText("");
        text_start.setText("");
        txt_end.setText("");
        txt_act.setText("");
//        com_cntry.setSelectedIndex(0);
    }
    public AcademicYear_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        com_respo = new RSMaterialComponent.RSComboBoxMaterial();
        com_sc = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        com_cntry = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jPanel1 = new javax.swing.JPanel();
        text_yrname = new necesario.TextField();
        txt_end = new necesario.TextField();
        text_ser1 = new necesario.TextField();
        btn_clr = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_save = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_updte = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_delte = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_start = new necesario.TextField();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        txt_act = new necesario.TextField();
        jLabel7 = new javax.swing.JLabel();

        com_respo.setBackground(new java.awt.Color(204, 0, 102));
        com_respo.setForeground(new java.awt.Color(255, 255, 255));
        com_respo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select responsible" }));
        com_respo.setColorMaterial(new java.awt.Color(255, 255, 255));

        com_sc.setBackground(new java.awt.Color(204, 0, 102));
        com_sc.setForeground(new java.awt.Color(255, 255, 255));
        com_sc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select School" }));
        com_sc.setColorMaterial(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Register Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 102));
        jLabel6.setText("School:");

        com_cntry.setBackground(new java.awt.Color(204, 0, 102));
        com_cntry.setForeground(new java.awt.Color(255, 255, 255));
        com_cntry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Country" }));
        com_cntry.setColorMaterial(new java.awt.Color(255, 255, 255));
        com_cntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_cntryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 102));
        jLabel2.setText("Country:");

        rSButtonMaterialIconTwo1.setText("tusa");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 58, 95));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AcademicYear_Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 120));

        text_yrname.setForeground(new java.awt.Color(31, 58, 95));
        text_yrname.setPlaceholder("Enter Yearname");
        text_yrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_yrnameActionPerformed(evt);
            }
        });
        getContentPane().add(text_yrname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 470, -1));

        txt_end.setForeground(new java.awt.Color(31, 58, 95));
        txt_end.setPlaceholder("Enter Ended");
        getContentPane().add(txt_end, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 470, -1));

        text_ser1.setForeground(new java.awt.Color(31, 58, 95));
        text_ser1.setPlaceholder("Enter Yearname");
        text_ser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ser1ActionPerformed(evt);
            }
        });
        getContentPane().add(text_ser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 142, 210, 50));

        btn_clr.setBackground(new java.awt.Color(255, 255, 255));
        btn_clr.setForeground(new java.awt.Color(204, 255, 255));
        btn_clr.setText("Clear");
        btn_clr.setBackgroundHover(new java.awt.Color(31, 58, 95));
        btn_clr.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_clr.setForegroundIconHover(new java.awt.Color(31, 58, 95));
        btn_clr.setForegroundText(new java.awt.Color(31, 58, 95));
        btn_clr.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btn_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 120, -1));

        btn_save.setBackground(new java.awt.Color(31, 58, 95));
        btn_save.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btn_save.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_save.setForegroundHover(new java.awt.Color(31, 58, 95));
        btn_save.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btn_save.setLabel("Insert");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 120, -1));

        btn_updte.setBackground(new java.awt.Color(255, 255, 255));
        btn_updte.setText("Update");
        btn_updte.setBackgroundHover(new java.awt.Color(31, 58, 95));
        btn_updte.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_updte.setForegroundIconHover(new java.awt.Color(31, 58, 95));
        btn_updte.setForegroundText(new java.awt.Color(31, 58, 95));
        btn_updte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btn_updte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updte, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 120, -1));

        btn_delte.setBackground(new java.awt.Color(31, 58, 95));
        btn_delte.setText("Delete");
        btn_delte.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btn_delte.setFocusable(false);
        btn_delte.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_delte.setForegroundHover(new java.awt.Color(31, 58, 95));
        btn_delte.setForegroundIcon(new java.awt.Color(31, 58, 95));
        btn_delte.setForegroundIconHover(new java.awt.Color(31, 58, 95));
        btn_delte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btn_delte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delte, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 95));
        jLabel3.setText("Yearname:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 58, 95));
        jLabel4.setText("Started:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(31, 58, 95));
        jLabel5.setText("Ended:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 120, 30));

        text_start.setForeground(new java.awt.Color(31, 58, 95));
        text_start.setPlaceholder("Enter Started");
        getContentPane().add(text_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 470, -1));

        rSButtonIconTwo1.setBackground(new java.awt.Color(31, 58, 95));
        rSButtonIconTwo1.setAutoscrolls(true);
        rSButtonIconTwo1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        rSButtonIconTwo1.setForegroundHover(new java.awt.Color(31, 58, 95));
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 60, 50));

        txt_act.setForeground(new java.awt.Color(31, 58, 95));
        txt_act.setPlaceholder("Enter Isactive");
        txt_act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_actActionPerformed(evt);
            }
        });
        getContentPane().add(txt_act, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 470, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 58, 95));
        jLabel7.setText("Isactive:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clrActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clrActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String oper="insert";
        String sql="call academicyear('" +text_yrname.getText()+ "','" +text_start.getText()+ "','"+txt_end.getText() +"',"+txt_act.getText() +",'" +oper+ "',null)";
        co.viewTable("call academicyear_view()", rSTableMetro1);
//        JOptionPane.showMessageDialog(null,sql);
        clear();
        co.setSql(sql);
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updteActionPerformed
        // TODO add your handling code here:
            String oper="update";
            String sql="call academicyear('" +text_yrname.getText()+ "','" +text_start.getText()+ "','"+txt_end.getText() +"',"+txt_act.getText() +",'" +oper+ "',"+id+")";
            co.viewTable("call academicyear_view()", rSTableMetro1);
            clear();
//        JOptionPane.showMessageDialog(null,sql);
            co.setSql(sql);
    }//GEN-LAST:event_btn_updteActionPerformed

    private void btn_delteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Ma hubtaa")==JOptionPane.YES_OPTION){
             String oper="delete";
             String sql="call academicyear('" +text_yrname.getText()+ "','" +text_start.getText()+ "','"+txt_end.getText() +"',"+txt_act.getText() +",'" +oper+ "',"+id+")";
             co.viewTable("call academicyear_view()", rSTableMetro1);
//             JOptionPane.showMessageDialog(null,sql);
             clear();
             co.setSql(sql);

        }
            
    }//GEN-LAST:event_btn_delteActionPerformed

    private void text_yrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_yrnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_yrnameActionPerformed

    private void com_cntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_cntryActionPerformed
        // TODO add your handling code here:
//        String array[]=com_cntry.getSelectedItem().toString().split("-");
//        country=array[0];
    }//GEN-LAST:event_com_cntryActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
        // TODO add your handling code here:
        String sql="SELECT y_no,yearname,started,ended,is_active FROM academicyear where y_no='"+text_ser1.getText()+"'";
        co.search(sql);
        try{
            if(co.rs.next()){
                id=co.rs.getString("y_no");
//                com_cntry.setSelectedItem(co.rs.getString("country"));
                text_yrname.setText(co.rs.getString("yearname"));
                text_start.setText(co.rs.getString("started"));
                txt_end.setText(co.rs.getString("ended"));
                txt_act.setText(co.rs.getString("is_active"));
            }else{
                JOptionPane.showMessageDialog(null, text_ser1.getText()+" Not found");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    private void text_ser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ser1ActionPerformed

    private void txt_actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_actActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_actActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcademicYear_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcademicYear_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcademicYear_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcademicYear_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcademicYear_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_clr;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_delte;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_save;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_updte;
    private RSMaterialComponent.RSComboBoxMaterial com_cntry;
    private RSMaterialComponent.RSComboBoxMaterial com_respo;
    private RSMaterialComponent.RSComboBoxMaterial com_sc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private necesario.TextField text_ser1;
    private necesario.TextField text_start;
    private necesario.TextField text_yrname;
    private necesario.TextField txt_act;
    private necesario.TextField txt_end;
    // End of variables declaration//GEN-END:variables

}
