/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package malyuun_university;

import java.sql.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Xamda Cumar
 */
public class Batchs_Form extends javax.swing.JFrame {

    /** Creates new form Locations_Form */
    codes co =new codes();
    String yr,id;
    public void clear(){
        text_ser1.setText("");
        text_bt.setText("");
//        text_sbco.setText("");
//        txtare.setText("");
        com_ac.setSelectedIndex(0);
    }
    public Batchs_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        co.fillComboBox(com_ac, "SELECT concat(y_no,'-', yearname) as sanad_dugsiyeedka from academicyear", "sanad_dugsiyeedka");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        com_respo = new RSMaterialComponent.RSComboBoxMaterial();
        com_sc = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        com_cntry = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel2 = new javax.swing.JLabel();
        txtare = new necesario.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_vllge1 = new necesario.TextField();
        text_sbco = new necesario.TextField();
        jPanel1 = new javax.swing.JPanel();
        text_bt = new necesario.TextField();
        text_ser1 = new necesario.TextField();
        btn_clr = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_save = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_updte = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btn_delte = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jLabel3 = new javax.swing.JLabel();
        rSButtonIconTwo1 = new RSMaterialComponent.RSButtonIconTwo();
        jLabel7 = new javax.swing.JLabel();
        com_ac = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel8 = new javax.swing.JLabel();
        rgdate = new com.toedter.calendar.JDateChooser();

        com_respo.setBackground(new java.awt.Color(204, 0, 102));
        com_respo.setForeground(new java.awt.Color(255, 255, 255));
        com_respo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select responsible" }));
        com_respo.setColorMaterial(new java.awt.Color(255, 255, 255));

        com_sc.setBackground(new java.awt.Color(204, 0, 102));
        com_sc.setForeground(new java.awt.Color(255, 255, 255));
        com_sc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select School" }));
        com_sc.setColorMaterial(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 102));
        jLabel1.setText("Register Date:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 102));
        jLabel6.setText("School:");

        com_cntry.setBackground(new java.awt.Color(204, 0, 102));
        com_cntry.setForeground(new java.awt.Color(255, 255, 255));
        com_cntry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Country" }));
        com_cntry.setColorMaterial(new java.awt.Color(255, 255, 255));
        com_cntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_cntryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 102));
        jLabel2.setText("Country:");

        txtare.setForeground(new java.awt.Color(204, 0, 102));
        txtare.setPlaceholder("Enter Area");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 102));
        jLabel4.setText("Village:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 102));
        jLabel5.setText("Area:");

        text_vllge1.setForeground(new java.awt.Color(204, 0, 102));
        text_vllge1.setPlaceholder("Enter Village");

        text_sbco.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        text_sbco.setForeground(new java.awt.Color(204, 0, 102));
        text_sbco.setPlaceholder("Enter code");
        text_sbco.setSelectionColor(new java.awt.Color(204, 0, 102));
        text_sbco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_sbcoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(31, 58, 95));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batchs_Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 120));

        text_bt.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        text_bt.setForeground(new java.awt.Color(31, 58, 95));
        text_bt.setPlaceholder("Enter batname");
        text_bt.setSelectionColor(new java.awt.Color(31, 58, 95));
        text_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_btActionPerformed(evt);
            }
        });
        getContentPane().add(text_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 470, -1));

        text_ser1.setForeground(new java.awt.Color(31, 58, 95));
        text_ser1.setPlaceholder("Enter Batchs");
        text_ser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ser1ActionPerformed(evt);
            }
        });
        getContentPane().add(text_ser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 142, 210, 50));

        btn_clr.setBackground(new java.awt.Color(255, 255, 255));
        btn_clr.setForeground(new java.awt.Color(204, 255, 255));
        btn_clr.setText("Clear");
        btn_clr.setBackgroundHover(new java.awt.Color(31, 58, 95));
        btn_clr.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_clr.setForegroundIconHover(new java.awt.Color(31, 58, 95));
        btn_clr.setForegroundText(new java.awt.Color(31, 58, 95));
        btn_clr.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLEAR);
        btn_clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 120, -1));

        btn_save.setBackground(new java.awt.Color(31, 58, 95));
        btn_save.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btn_save.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_save.setForegroundHover(new java.awt.Color(31, 58, 95));
        btn_save.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        btn_save.setLabel("Insert");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        getContentPane().add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 120, -1));

        btn_updte.setBackground(new java.awt.Color(255, 255, 255));
        btn_updte.setText("Update");
        btn_updte.setBackgroundHover(new java.awt.Color(31, 58, 95));
        btn_updte.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_updte.setForegroundIconHover(new java.awt.Color(31, 58, 95));
        btn_updte.setForegroundText(new java.awt.Color(31, 58, 95));
        btn_updte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        btn_updte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_updte, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 120, -1));

        btn_delte.setBackground(new java.awt.Color(31, 58, 95));
        btn_delte.setText("Delete");
        btn_delte.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btn_delte.setFocusable(false);
        btn_delte.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        btn_delte.setForegroundHover(new java.awt.Color(31, 58, 95));
        btn_delte.setForegroundIcon(new java.awt.Color(31, 58, 95));
        btn_delte.setForegroundIconHover(new java.awt.Color(31, 58, 95));
        btn_delte.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btn_delte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_delte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 58, 95));
        jLabel3.setText("BatName:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 120, 30));

        rSButtonIconTwo1.setBackground(new java.awt.Color(31, 58, 95));
        rSButtonIconTwo1.setAutoscrolls(true);
        rSButtonIconTwo1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        rSButtonIconTwo1.setForegroundHover(new java.awt.Color(31, 58, 95));
        rSButtonIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconTwo1ActionPerformed(evt);
            }
        });
        getContentPane().add(rSButtonIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 60, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(31, 58, 95));
        jLabel7.setText("AcademicYear:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 140, 30));

        com_ac.setBackground(new java.awt.Color(31, 58, 95));
        com_ac.setForeground(new java.awt.Color(255, 255, 255));
        com_ac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select AcademicYear" }));
        com_ac.setColorMaterial(new java.awt.Color(255, 255, 255));
        com_ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_acActionPerformed(evt);
            }
        });
        getContentPane().add(com_ac, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 470, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(31, 58, 95));
        jLabel8.setText("Register Date:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 140, 30));

        rgdate.setBackground(new java.awt.Color(31, 58, 95));
        rgdate.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(rgdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 470, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clrActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clrActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        Date dl =new Date(rgdate.getDate().getTime());
        String oper="insert";
        String sql="call batchs('"+text_bt.getText()+ "'," +yr+",'"+dl+"','" +oper+ "',null)";
        clear();
//        JOptionPane.showMessageDialog(null,sql);
        co.setSql(sql);
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_updteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updteActionPerformed
        // TODO add your handling code here:
            Date dl =new Date(rgdate.getDate().getTime());
            String oper="update";
            String sql="call batchs('"+text_bt.getText()+ "'," +yr+",'"+dl+"','" +oper+ "',"+id+")";
            clear();
            
//        JOptionPane.showMessageDialog(null,sql);
            co.setSql(sql);
    }//GEN-LAST:event_btn_updteActionPerformed

    private void btn_delteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delteActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(null, "Ma hubtaa")==JOptionPane.YES_OPTION){
            Date dl =new Date(rgdate.getDate().getTime());
             String oper="delete";
            String sql="call batchs('"+text_bt.getText()+ "'," +yr+",'"+dl+"','" +oper+ "',"+id+")";
            clear();
            
//             JOptionPane.showMessageDialog(null,sql);
             co.setSql(sql);

        }
            
    }//GEN-LAST:event_btn_delteActionPerformed

    private void text_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_btActionPerformed

    private void com_cntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_cntryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_com_cntryActionPerformed

    private void rSButtonIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconTwo1ActionPerformed
        // TODO add your handling code here:
        String sql="SELECT b_no,batname, concat(a.y_no,'-',yearname) as sanad_dugsiyeedka, b.reg_date FROM batchs b ,academicyear a WHERE a.y_no=b.y_no and b_no='"+text_ser1.getText()+"'";
        co.search(sql);
        try{
            if(co.rs.next()){
                id=co.rs.getString("b_no");
//                com_cntry.setSelectedItem(co.rs.getString("country"));
                text_bt.setText(co.rs.getString("batname"));
                com_ac.setSelectedItem(co.rs.getString("sanad_dugsiyeedka"));
                rgdate.setDate(co.rs.getDate("reg_date"));
//                text_sbco.setText(co.rs.getString("subcode"));
//                txtare.setText(co.rs.getString("area"));
            }else{
                JOptionPane.showMessageDialog(null, text_ser1.getText()+" Not found");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_rSButtonIconTwo1ActionPerformed

    private void text_ser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ser1ActionPerformed

    private void text_sbcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_sbcoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_sbcoActionPerformed

    private void com_acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_acActionPerformed
        // TODO add your handling code here:S
        String array[]=com_ac.getSelectedItem().toString().split("-");
        yr=array[0];

    }//GEN-LAST:event_com_acActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batchs_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batchs_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batchs_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batchs_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batchs_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_clr;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_delte;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_save;
    private RSMaterialComponent.RSButtonMaterialIconTwo btn_updte;
    private RSMaterialComponent.RSComboBoxMaterial com_ac;
    private RSMaterialComponent.RSComboBoxMaterial com_cntry;
    private RSMaterialComponent.RSComboBoxMaterial com_respo;
    private RSMaterialComponent.RSComboBoxMaterial com_sc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSButtonIconTwo rSButtonIconTwo1;
    private com.toedter.calendar.JDateChooser rgdate;
    private necesario.TextField text_bt;
    private necesario.TextField text_sbco;
    private necesario.TextField text_ser1;
    private necesario.TextField text_vllge1;
    private necesario.TextField txtare;
    // End of variables declaration//GEN-END:variables

}
